server:
  port: 8085

# local Profile
spring:
  application:
    name: UserMicroService
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: noname
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis


---

# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: UserMicroService
  datasource:
    url: jdbc:postgresql://postgres:5432/user
    username: noname
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  data:
    redis:
      host: redis_cache
      port: 6379
  cache:
    type: redis