server:
  port: 8080

spring:
  application:
    name: logging-service
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: localhost
      port: 27017
      database: logs
      authentication-database: admin
      username: mongodb
      password: mongodb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO