server:
  port: 8085

spring:
  profiles:
    active: local

---

# local Profile
spring:
  application:
    name: NotesMicroService
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/notes?authSource=admin
      database: notes
      port: 27017

---

# Docker Profile
spring:
  application:
    name: NotesMicroService
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://root:example@mongodb:27017/notes?authSource=admin
      database:notes