apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag
  template:
    metadata:
      labels:
        app: tag
    spec:
      containers:
      - name: tag
        image: tag:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/tag
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: tag
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
  selector:
    app: tag 