apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: notification:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://root:example@mongodb:27017/notification?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    app: notification 