apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: notes:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://root:example@mongodb:27017/notes?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: notes
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: notes 