version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: tag-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tag
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tag-network

  tag-service:
    build: .
    container_name: tag-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tag
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8084:8084"
    networks:
      - tag-network

networks:
  tag-network:
    driver: bridge

volumes:
  postgres-data:
