server:
  port: 8084

spring:
  profiles:
    active: local
  application:
    name: reminder-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  logging:
    level:
      root: INFO
      org.springframework.amqp: DEBUG
      org.springframework.data.mongodb: DEBUG
      com.example.reminder: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

---
# Local Profile
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/reminder?authSource=admin

---

# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://root:example@mongodb:27017/reminder?authSource=admin
