services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: noname
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:latest
    container_name: redisCache
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight
    ports:
      - "5540:5540"
    restart: always

#  app:
#    build: .
#    container_name: userMicroService
#    depends_on:
#      - postgres
#      - redis_cache
#    ports:
#      - "8085:8085"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker  # Activate the docker profile
#      SPRING_DATA_REDIS_HOST: redis_cache
#      SPRING_DATA_REDIS_PORT: 6379
